spring.application.name=naming-server

server.port = 8761

eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never
server.error.include-exception=false