spring.application.name=api-gateway

server.port = 8765

eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka

spring.main.web-application-type=reactive

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never
server.error.include-exception=false
