spring.application.name=crypto-conversion
server.port=8500

eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never
server.error.include-exception=false